# File: .github/workflows/template-sync.yml

on:
  # cronjob trigger
  schedule:
  - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # https://github.com/actions/checkout#usage
        uses: actions/checkout@v4

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: sourabhmandal/nextjs_zod_drizzle_fetch_template
          upstream_branch: main # defaults to main
          pr_labels: template_sync,latest # defaults to template_sync